(function(){
  "use strict";
  var C=window.JGM4Calc, form=document.querySelector("[data-calculator]");
  function track(name,status){window.dataLayer=window.dataLayer||[];window.dataLayer.push({event:name,calculator_type:tool,diagnosis_type:status||undefined,page_path:location.pathname})}
  if(!form){document.addEventListener("click",function(e){var link=e.target.closest("[data-event]");if(link)track(link.dataset.event)});track("view_logistics_tools");return}
  var tool=form.dataset.calculator,result=document.querySelector("#resultado"),packages=document.querySelector("#packages"),packageCount=1;
  function field(name){return form.elements[name]}
  function value(name){return C.parseBR(field(name).value)}
  function error(el,message){el.setAttribute("aria-invalid",message?"true":"false");var box=document.getElementById(el.id+"-error");if(box)box.textContent=message||""}
  function positive(el,label,integer){var v=C.parseBR(el.value),msg="";if(!Number.isFinite(v)||v<=0)msg="Informe "+label+" maior que zero.";else if(integer&&!Number.isInteger(v))msg="Informe uma quantidade inteira maior que zero.";error(el,msg);return msg?NaN:v}
  function nonNegative(el,label,integer){var v=C.parseBR(el.value),msg="";if(!Number.isFinite(v)||v<0)msg="Informe "+label+" igual ou maior que zero.";else if(integer&&!Number.isInteger(v))msg="Informe uma quantidade inteira igual ou maior que zero.";error(el,msg);return msg?NaN:v}
  function goal(el){var v=positive(el,"um percentual",false);if(Number.isFinite(v)&&v>100){error(el,"Informe um percentual de até 100%.");return NaN}if(Number.isFinite(v)&&v<.1)document.getElementById(el.id+"-error").textContent="Esse percentual é muito baixo. Confirme a meta.";return v}
  function escapeHTML(value){var node=document.createElement("span");node.textContent=String(value);return node.innerHTML}
  function metric(label,val){return '<div class="lf-metric"><span>'+escapeHTML(label)+'</span><strong>'+escapeHTML(val)+'</strong></div>'}
  function statusLabel(s){return s==="good"?"✓ Saudável":s==="attention"?"⚠ Atenção":"! Crítico"}
  function render(lead,status,metrics,explanation,plan,cta){
    result.innerHTML='<div class="lf-print-meta">JGM4 Consultoria · '+new Date().toLocaleDateString("pt-BR")+' · '+location.href+'</div><span class="lf-status '+status+'">'+statusLabel(status)+'</span><p class="lf-result-lead" tabindex="-1">'+lead+'</p><div class="lf-metrics">'+metrics.join("")+'</div><p>'+explanation+'</p><h3>Plano de ação</h3><ol class="lf-plan">'+plan.map(function(x){return"<li>"+x+"</li>"}).join("")+'</ol>'+cta+'<p class="lf-help">Estimativa gerencial. Confirme regras comerciais, margens e condições da operação antes de decidir.</p><div class="lf-actions"><button type="button" class="lf-button lf-button-secondary" data-copy>Copiar resultado</button><button type="button" class="lf-button lf-button-secondary" data-whatsapp>Compartilhar no WhatsApp</button><button type="button" class="lf-button lf-button-quiet" data-print>Imprimir</button></div>';
    result.hidden=false;
    var copy=result.cloneNode(true),actions=copy.querySelector(".lf-actions"),offer=copy.querySelector(".lf-cta"),printMeta=copy.querySelector(".lf-print-meta");
    if(actions)actions.remove();if(offer)offer.remove();if(printMeta)printMeta.remove();
    result.dataset.copy=document.title.replace(/\s*\|\s*JGM4.*$/,"")+"\n"+copy.innerText.trim();
    result.querySelector(".lf-result-lead").focus();track("complete_calculation",status)
  }
  function packageData(){
    var rows=[],bad=false;
    packages.querySelectorAll(".lf-package").forEach(function(row){
      var q=function(n,l,int){var el=row.querySelector('[name="'+n+'"]'),v=positive(el,l,int);if(!Number.isFinite(v))bad=true;return v};
      var length=q("length","um comprimento",false),width=q("width","uma largura",false),height=q("height","uma altura",false),quantity=q("quantity","uma quantidade",true);
      [row.querySelector('[name="length"]'),row.querySelector('[name="width"]'),row.querySelector('[name="height"]')].forEach(function(el){if(C.parseBR(el.value)>10000)document.getElementById(el.id+"-error").textContent="Esse valor parece muito elevado. Confirme a unidade selecionada.";});
      rows.push({name:row.querySelector('[name="packageName"]').value||"Embalagem",length:length,width:width,height:height,quantity:quantity,unit:row.querySelector('[name="unit"]').value});
    });return bad?null:rows
  }
  function calculate(){
    if(tool==="cubage"){
      var rows=packageData(),real=positive(field("realWeight"),"um peso",false),factor=field("factor").value==="custom"?positive(field("customFactor"),"um fator de cubagem",false):C.parseBR(field("factor").value);if(!rows||!Number.isFinite(real)||!Number.isFinite(factor))return;
      var r=C.cubage(rows,real,factor),cubed=r.cubedWeight>r.realWeight,status=cubed&&r.differencePercent>25?"critical":cubed?"attention":"good";
      var rowMetrics=r.rows.map(function(p,i){return metric((p.name||"Embalagem "+(i+1))+" · volume",C.number(p.totalVolume,4)+" m³")});
      var comparison=value("comparisonFactor");
      if(Number.isFinite(comparison)&&comparison>0&&comparison!==factor)rowMetrics.push(metric("Peso com fator "+C.number(comparison,2),C.number(r.totalVolume*comparison,2)+" kg ("+(comparison>factor?"+":"")+C.number(r.totalVolume*(comparison-factor),2)+" kg)"));
      render((cubed?"O peso cubado é superior ao peso real.":"O peso real é igual ou superior ao peso cubado.")+" Nesta simulação, o peso taxável estimado é "+C.number(r.consideredWeight,2)+" kg, sujeito às regras da transportadora.",status,[metric("Volumes",C.number(r.totalPackages)),metric("Volume total",C.number(r.totalVolume,4)+" m³"),metric("Peso real",C.number(r.realWeight,2)+" kg"),metric("Peso cubado",C.number(r.cubedWeight,2)+" kg"),metric("Peso taxável estimado",C.number(r.consideredWeight,2)+" kg"),metric("Diferença",C.number(r.difference,2)+" kg · "+C.percent(r.differencePercent))].concat(rowMetrics),"O volume total é multiplicado pelo fator informado. Em muitos contratos, o peso taxável corresponde ao maior entre peso real e cubado; confirme fator, arredondamento e regra comercial.",cubed?["Revise dimensões e espaços vazios da embalagem.","Avalie consolidação ou desmontagem quando viável.","Compare fatores e confirme a regra da transportadora."]:["Confirme o peso aferido e a regra contratual.","Compare modalidades e condições da transportadora.","Use a cubagem na conferência da fatura."],cta("Quer aprofundar a análise de cubagem e fretes?","Conheça o eBook Engenharia de Fretes","ebook-engenharia-de-fretes.html","click_ebook_cta"));
    }else if(tool==="freight"){
      var order=positive(field("order"),"um valor de pedido",false),freightValue=positive(field("freight"),"um valor de frete",false),g=goal(field("goal"));if(![order,freightValue,g].every(Number.isFinite))return;
      var f=C.freight(order,freightValue,g),need=f.reduction>0;
      render("Seu frete representa "+C.percent(f.realPercent)+" do pedido. A meta informada foi "+C.percent(g)+".",f.status,[metric("Pedido",C.money(order)),metric("Frete",C.money(freight)),metric("Percentual real",C.percent(f.realPercent)),metric("Meta",C.percent(g)),metric("Diferença",C.number(f.differencePoints,2)+" p.p."),metric("Frete máximo",C.money(f.maxFreight)),metric("Redução matemática",need?C.money(f.reduction):"Não necessária")],"Não existe percentual ideal universal: margem, região, ticket médio, produto, serviço, concorrência e estratégia comercial precisam entrar na análise.",need?["Avalie consolidar pedidos.","Verifique se o frete pode ser negociado até "+C.money(f.maxFreight)+".","Revise pedido mínimo, CIF/FOB e margem."]:["Monitore a meta por região e canal.","Valide a margem mesmo com o indicador saudável.","Compare outras ferramentas da JGM4."],f.status==="critical"?cta("Precisa revisar os custos da operação?","Conheça a consultoria de redução de custos","reducao-custos-logisticos.html","click_consulting_cta"):cta("Aprofunde sua gestão de fretes","Conheça Engenharia do Frete","ebook-engenharia-de-fretes.html","click_ebook_cta"));
    }else if(tool==="accuracy"){
      var mode=field("accuracyMode").value;
      if(mode==="items"){
        var total=positive(field("totalItems"),"o total de itens",true),correct=positive(field("correctItems"),"os itens sem divergência",true);if(![total,correct].every(Number.isFinite))return;if(correct>total){error(field("correctItems"),"Os itens corretos não podem superar o total contado.");return}
        var ai=C.accuracyByItems(total,correct),as=ai.accuracy>=98?"good":ai.accuracy>=95?"attention":"critical";
        render("A acuracidade estimada por itens é "+C.percent(ai.accuracy)+".",as,[metric("Itens contados",C.number(total)),metric("Itens sem divergência",C.number(correct)),metric("Itens divergentes",C.number(ai.divergent)),metric("Acuracidade",C.percent(ai.accuracy)),metric("Divergência",C.percent(ai.divergence))],"A leitura por itens mostra quantos SKUs fecharam, mas não revela sozinha o impacto financeiro ou a criticidade dos produtos.",["Separe divergências por causa e endereço.","Conte novamente os itens críticos.","Revise recebimento, movimentação e expedição."],cta("Precisa investigar as causas das divergências?","Solicitar diagnóstico de estoque","diagnostico-de-estoque.html","click_stock_diagnosis"));
      }else if(mode==="quantity"){
        var systemQty=positive(field("systemQuantity"),"a quantidade do sistema",false),physicalQty=nonNegative(field("physicalQuantity"),"a quantidade física",false);if(![systemQty,physicalQty].every(Number.isFinite))return;
        var aq=C.accuracyByQuantity(systemQty,physicalQty),qs=aq.accuracy>=98?"good":aq.accuracy>=95?"attention":"critical";
        render("A acuracidade estimada por quantidade é "+C.percent(aq.accuracy)+".",qs,[metric("Quantidade no sistema",C.number(systemQty,2)),metric("Quantidade física",C.number(physicalQty,2)),metric("Diferença",C.number(aq.difference,2)),metric("Diferença absoluta",C.number(aq.absoluteDifference,2)),metric("Acuracidade",C.percent(aq.accuracy)),metric("Divergência",C.percent(aq.divergence))],"O cálculo compara uma posição consolidada. Analise cada SKU separadamente quando valores, lotes ou criticidade forem diferentes.",["Valide unidade de medida e conversões.","Revise ajustes e movimentações sem registro.","Repita a contagem com segregação por endereço."],cta("Estoque físico diferente do sistema?","Ver causas e plano de correção","../blog/estoque-nao-bate.html","click_stock_article"));
      }else{
        var systemValue=positive(field("systemValue"),"o valor sistêmico",false),physicalValue=nonNegative(field("physicalValue"),"o valor físico",false);if(![systemValue,physicalValue].every(Number.isFinite))return;
        var av=C.accuracyByValue(systemValue,physicalValue),vs=av.accuracy>=98?"good":av.accuracy>=95?"attention":"critical";
        render("A divergência financeira estimada é "+C.money(av.financialDifference)+".",vs,[metric("Valor sistêmico",C.money(systemValue)),metric("Valor físico",C.money(physicalValue)),metric("Diferença financeira",C.money(av.financialDifference)),metric("Acuracidade estimada",C.percent(av.accuracy)),metric("Divergência",C.percent(av.divergence))],"Uma acuracidade financeira alta pode esconder muitos itens de baixo valor divergentes. Combine as leituras física, quantitativa e financeira.",["Classifique divergências por valor e criticidade.","Confirme custos unitários e saldos bloqueados.","Investigue causas antes de realizar ajustes."],cta("Quer estruturar uma rotina de acuracidade?","Conhecer a consultoria de estoque","consultoria-gestao-estoque.html","click_stock_consulting"));
      }
    }else if(tool==="capacity"){
      var pallets=positive(field("pallets"),"a quantidade de paletes",false),growth=nonNegative(field("growth"),"o crescimento previsto",false),occupancy=goal(field("occupancy")),levels=positive(field("levels"),"os níveis de armazenagem",true),picking=positive(field("pickingPositions"),"as posições de picking",true);if(![pallets,growth,occupancy,levels,picking].every(Number.isFinite))return;
      var cap=C.distributionCapacity(pallets,growth,occupancy,levels,picking),dailyOrders=positive(field("dailyOrders"),"os pedidos por dia",true),dailySku=positive(field("dailySku"),"os SKUs separados por dia",true),receipts=positive(field("receipts"),"os recebimentos por dia",true),shipments=positive(field("shipments"),"as expedições por dia",true);if(![dailyOrders,dailySku,receipts,shipments].every(Number.isFinite))return;
      var cs=occupancy>90?"critical":occupancy>85?"attention":"good";
      render("A estimativa inicial indica "+C.number(cap.requiredPositions)+" posições-palete para absorver estoque, crescimento e ocupação de segurança.",cs,[metric("Paletes atuais",C.number(pallets)),metric("Com crescimento",C.number(cap.growthPositions)),metric("Posições necessárias",C.number(cap.requiredPositions)),metric("Reserva por ocupação",C.number(cap.reservePositions)),metric("Posições por nível no piso",C.number(cap.floorPositions)),metric("Picking / capacidade",C.percent(cap.pickingShare)),metric("Pedidos por dia",C.number(dailyOrders)),metric("SKUs separados por dia",C.number(dailySku)),metric("Recebimentos / expedições",C.number(receipts)+" / "+C.number(shipments))],"A estimativa dimensiona posições, não área construída. Corredores, pilares, docas, stage, equipamentos, segurança, incêndio e perfil dimensional exigem projeto técnico.",["Valide estoque máximo por SKU e curva de giro.","Dimensione picking e pulmão separadamente.","Meça fluxos, equipamentos, docas e áreas de stage."],cta("Precisa transformar a estimativa em projeto?","Solicitar projeto de dimensionamento do CD","consultoria-centro-distribuicao.html","click_cd_consulting"));
    }else{
      var fv=positive(field("freight"),"um valor de frete",false),gg=goal(field("goal")),op=positive(field("operationalCost"),"um custo operacional",false),gm=goal(field("grossMargin")),current=positive(field("current"),"um valor médio de pedido",false);if(![fv,gg,op,gm,current].every(Number.isFinite))return;
      var m=C.minimumAdvanced(fv,gg,op,gm,current),has=m.hasCurrent,lead=m.difference>0?"Faltam "+C.money(m.additional)+" para o pedido atual atingir o mínimo baseado no frete.":"O pedido atual atinge o mínimo baseado no frete e possui "+C.money(m.margin)+" acima dele.";
      render(lead,m.status,[metric("Frete",C.money(fv)),metric("Meta de frete",C.percent(gg)),metric("Pedido mínimo",C.money(m.minimum)),metric("Pedido médio atual",C.money(current)),metric("Frete no pedido",C.percent(m.currentPercent)),metric("Custo operacional",C.money(op)+" · "+C.percent(m.operationalPercent)),metric("Frete + operação",C.percent(m.logisticsPercent)),metric("Margem bruta informada",C.percent(gm)),metric("Margem após custos logísticos",C.percent(m.marginAfterLogistics))],"O pedido mínimo principal usa frete ÷ percentual máximo. A margem após custos logísticos é uma simulação simplificada, sem impostos, comissões, devoluções ou custo do produto.",m.marginWarning?["Revise imediatamente a margem e os custos informados.","Avalie consolidar pedidos e segmentar regiões.","Valide o cálculo com financeiro e comercial."]:m.difference>0?["Avalie consolidar itens ou pedidos.","Revise a política por região e o custo do frete.","Analise margem e condições CIF/FOB."]:["Use o valor como referência, não como regra isolada.","Revise o mínimo quando fretes ou margens mudarem.","Comunique a política comercial com clareza."],cta("Quer revisar sua política de fretes?","Solicitar análise da política de fretes","auditoria-de-fretes.html","click_freight_analysis"));
    }
  }
  function cta(text,label,url,event){return '<div class="lf-cta"><h3>'+text+'</h3><a class="lf-button" href="'+url+'" data-event="'+event+'">'+label+'</a></div>'}
  function row(values){
    packageCount++;var id="pkg"+packageCount,div=document.createElement("div");div.className="lf-package";div.innerHTML='<div class="lf-package-head"><strong>Tipo de embalagem '+packageCount+'</strong><button type="button" class="lf-button lf-button-quiet" data-remove>Remover</button></div><div class="lf-form-grid"><div class="lf-field"><label for="'+id+'name">Identificação (opcional)</label><input id="'+id+'name" name="packageName" autocomplete="off"></div>'+["length:Comprimento","width:Largura","height:Altura"].map(function(x){var p=x.split(":");return '<div class="lf-field"><label for="'+id+p[0]+'">'+p[1]+'</label><input inputmode="decimal" id="'+id+p[0]+'" name="'+p[0]+'" aria-describedby="'+id+p[0]+'-error"><span class="lf-error" id="'+id+p[0]+'-error"></span></div>'}).join("")+'<div class="lf-field"><label for="'+id+'unit">Unidade</label><select id="'+id+'unit" name="unit"><option value="cm">cm</option><option value="m">m</option></select></div><div class="lf-field"><label for="'+id+'quantity">Quantidade</label><input inputmode="numeric" id="'+id+'quantity" name="quantity" aria-describedby="'+id+'quantity-error"><span class="lf-error" id="'+id+'quantity-error"></span></div></div><p class="lf-inline-result" aria-live="polite">Preencha medidas e quantidade para ver o volume.</p>';packages.appendChild(div)
  }
  function updatePackageVolumes(){
    if(!packages)return;
    packages.querySelectorAll(".lf-package").forEach(function(p){
      var get=function(name){return C.parseBR(p.querySelector('[name="'+name+'"]').value)},q=get("quantity"),data={length:get("length"),width:get("width"),height:get("height"),quantity:q,unit:p.querySelector('[name="unit"]').value},unit=C.packageVolume(data),box=p.querySelector(".lf-inline-result");
      if(box)box.textContent=[unit,q].every(function(v){return Number.isFinite(v)&&v>0})?"Volume unitário: "+C.number(unit,6)+" m³ · volume total: "+C.number(unit*q,6)+" m³":"Preencha medidas e quantidade para ver o volume.";
    })
  }
  form.addEventListener("submit",function(e){e.preventDefault();calculate()});
  form.addEventListener("input",updatePackageVolumes);
  form.addEventListener("change",function(){updatePackageVolumes();var custom=document.getElementById("custom-factor-field");if(custom)custom.hidden=field("factor").value!=="custom"});
  form.addEventListener("focusin",function(){if(!form.dataset.started){form.dataset.started="1";track("start_calculator")}},{once:true});
  form.addEventListener("click",function(e){
    if(e.target.closest("[data-example]")){if(tool==="cubage"){field("length").value="61";field("width").value="48";field("height").value="34";field("quantity").value="100";field("realWeight").value="140";field("factor").value="300"}else if(tool==="freight"){field("order").value="5000";field("freight").value="450";field("goal").value="6"}else if(tool==="minimum"){field("freight").value="300";field("goal").value="5";field("operationalCost").value="80";field("grossMargin").value="28";field("current").value="4800";field("region").value="Sudeste"}else if(tool==="accuracy"){field("accuracyMode").value="items";field("totalItems").value="1000";field("correctItems").value="970";updateAccuracyMode()}else if(tool==="capacity"){field("pallets").value="1200";field("growth").value="20";field("levels").value="5";field("occupancy").value="85";field("pickingPositions").value="180";field("receipts").value="14";field("shipments").value="18";field("dailyOrders").value="320";field("dailySku").value="1450"}track("use_example")}
    if(e.target.closest("[data-clear]")){if(confirm("Limpar todos os valores e o resultado?")){form.reset();result.hidden=true;if(packages)packages.querySelectorAll(".lf-package:not(:first-child)").forEach(function(x){x.remove()});var custom=document.getElementById("custom-factor-field");if(custom)custom.hidden=true;updatePackageVolumes();track("clear_calculator")}}
    if(e.target.closest("[data-add]")){var count=packages.querySelectorAll(".lf-package").length,limit=document.getElementById("package-limit");if(count<10){row();if(limit)limit.textContent="";track("add_package_type")}else if(limit)limit.textContent="O limite desta versão é de 10 tipos de embalagem."}
    var remove=e.target.closest("[data-remove]");if(remove&&packages.querySelectorAll(".lf-package").length>1)remove.closest(".lf-package").remove()
  });
  function updateAccuracyMode(){
    if(tool!=="accuracy")return;
    var mode=field("accuracyMode").value;
    form.querySelectorAll("[data-accuracy-fields]").forEach(function(box){box.hidden=box.dataset.accuracyFields!==mode});
    result.hidden=true;
  }
  if(tool==="accuracy"){field("accuracyMode").addEventListener("change",updateAccuracyMode);updateAccuracyMode()}
  result.addEventListener("click",function(e){
    if(e.target.closest("[data-copy]")){navigator.clipboard.writeText(result.dataset.copy+"\nEstimativa — JGM4 Consultoria\n"+location.href).then(function(){e.target.textContent="Resultado copiado"});track("copy_result")}
    if(e.target.closest("[data-whatsapp]")){if(confirm("Os principais resultados serão enviados ao WhatsApp. Continuar?")){track("share_whatsapp");window.open("https://wa.me/?text="+encodeURIComponent(result.dataset.copy+"\nEstimativa — JGM4 Consultoria\n"+location.href),"_blank","noopener")}}
    if(e.target.closest("[data-print]")){track("print_result");window.print()}
    var link=e.target.closest("[data-event]");if(link)track(link.dataset.event,result.querySelector(".lf-status").classList[1])
  });
  document.addEventListener("click",function(e){var link=e.target.closest("[data-event]");if(link&&!result.contains(link))track(link.dataset.event)});
  track("view_logistics_tools");
})();
